name: Build and test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with testing
        run: ./gradlew check --console rich --info

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests
          path: ./*/build/reports/tests/test

      - name: JaCoCo test report
        run: ./gradlew jacocoTestReport

      - uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: ./*/build/reports/jacoco/test
